### ISSUE TITLE
'Compressor' object has no attribute 'process'

### ISSUE THREAD

**Issue by kylebarron** [fullonic/brotli-asgi#10]
I'm trying to integrate your package and getting `'Compressor' object has no attribute 'process'` errors. Specifically here:

https://github.com/fullonic/brotli-asgi/blob/708e57ae4d0cd5101361de500dc642119d2d1890/brotli_asgi/__init__.py#L122

For me in a REPL, this doesn't exist:

```py
import brotli
br_file = brotli.Compressor()
br_file.process()
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-c812ff5613f7> in <module>
----> 1 br_file.process()

AttributeError: 'Compressor' object has no attribute 'process'
```

Brotli version: 1.0.7.

**Comment by kylebarron** [comment]
FYI: I get the same errors when running your tests locally

**Comment by fullonic** [comment]
Hey @kylebarron do you have `brotlipy` installed?

**Comment by kylebarron** [comment]
See the linked PR.

I didn't even think to check at first if I had brotlipy installed; it's really annoying when packages export a different name...

**Comment by fullonic** [comment]
I just red you PR. Yep, I spent a lot of time trying to figure out how to fix the naming conflict. Thanks for the PR.
