### ISSUE TITLE
Docstring is wrong

### ISSUE THREAD

**Issue by drnextgis** [fullonic/brotli-asgi#15]
According to the [code](https://github.com/fullonic/brotli-asgi/blob/117fb82081af2b7e490a914cefd80472588155b5/brotli_asgi/__init__.py#L29)  default mode is `text`, but [here](https://github.com/fullonic/brotli-asgi/blob/117fb82081af2b7e490a914cefd80472588155b5/brotli_asgi/__init__.py#L39) stated that it is `generic`.

**Comment by fullonic** [comment]
Thanks for reporting it @drnextgis
