### ISSUE TITLE
Adding brotli-asgi to the conda-forge feedstock

### ISSUE THREAD

**Issue by dcfidalgo** [fullonic/brotli-asgi#18]
Hi @fullonic Thank you for this awesome package. We are using it as a dependency in our opensource [library Rubrix](https://github.com/recognai/rubrix). Since we want to support installations via `conda`, we need your package in the conda-forge feedstock. I opened [a PR](https://github.com/conda-forge/staged-recipes/pull/18114) for this, I hope this is ok with you. Let me know if you want me to include you as one of the maintainers of the feedstock.

**Comment by fullonic** [comment]
Hi @dcfidalgo. Thanks for reaching out. For sure it's fine for me having this package as part of conda-forge. 
Thanks for your [PR](https://github.com/conda-forge/staged-recipes/pull/18114).

And about including me on the maintainer's list, I'm okay to be part or not... To be honest, I don't use conda, but if normally all conda packages maintainers are part of the feedstock maintainers list, I'm fine being part as well.  
I will start using `brotli-asgi` in my day job, so I will be able to maintain it, solve possible issues and merge PRs

Cheers :smiley:

**Comment by dcfidalgo** [comment]
> I will start using brotli-asgi in my day job, so I will be able to maintain it, solve possible issues and merge PRs

Awesome, nice to hear that :)

> And about including me on the maintainer's list, I'm okay to be part or not... To be honest, I don't use conda, but if normally all conda packages maintainers are part of the feedstock maintainers list, I'm fine being part as well.

Not necessarily, but if you don't mind, I will include you, just in case you want to get more involved at some point.

**Comment by fullonic** [comment]
> Not necessarily, but if you don't mind, I will include you, just in case you want to get more involved at some point.

All right. Thanks :smiley:

**Comment by fullonic** [comment]
Thanks again @dcfidalgo for adding this library to conda-forge
