### ISSUE TITLE
How can I exempt a specific route from using compression?

### ISSUE THREAD

**Issue by erichaus** [fullonic/brotli-asgi#19]
Using this middleware in my starlette app but curious if anyone knows how to exclude a specific route/endpoint from using compression? e.g. for a StreamingResponse that returns a zip file

**Comment by fullonic** [comment]
Hi @hoIIer. Right now it seems not possible but it is something that would definitely be a great feature. I'm looking to add this in the near future, maybe until the end of the month, once I get some free time. It shouldn't be difficult. Let's see what ideas/suggestions pop up from your [question in the starlette repo](https://github.com/encode/starlette/discussions/1661), and we could port them into this middleware. It's okay for you?

**Comment by erichaus** [comment]
hey @fullonic that sounds great! Want me to close this or leave it open?

**Comment by fullonic** [comment]
We can keep it open until we have implemented the mechanism to ignore certain endpoints from being compressed.

**Comment by fullonic** [comment]
Hi @hoIIer , would you like to test PR #21? Thanks

**Comment by bshakur8** [comment]
Hi @fullonic , I tested it and it works fine. Any plans to merge this?

**Comment by fullonic** [comment]
Great! Thanks for your feedback @bshakur8 . Next week I will integrate this new feature and release a new version to pypi

**Comment by SavoX2** [comment]
Is it ready to be merged right now? In dire need of this feature @fullonic

**Comment by fullonic** [comment]
Hi @SavoX2. I just merged into master but I'm not able to generate a new release until Friday.

**Comment by fullonic** [comment]
Hi @SavoX2 ! Just released version 1.2.0 on pypi which contains this new feature.
