### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by erichaus** [fullonic/brotli-asgi#8]
```
>>> from brotli_asgi import BrotliMiddleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'brotli_asgi'
```
I did `pip install brotli-middleware` on python 3.8

**Comment by kylebarron** [comment]
It should be `from brotli_middleware import BrotliMiddleware`

**Comment by erichaus** [comment]
ah ok will try that, looks like the docs are incorrect then https://github.com/fullonic/brotli-asgi#starlette

thanks

**Comment by erichaus** [comment]
@kylebarron thanks that worked, hitting a separate issue that I'll open ticket for, readme needs update for import path

**Comment by kylebarron** [comment]
Actually it looks like [`brotli-asgi`](https://pypi.org/project/brotli-asgi/) is newer than [`brotli-middleware`](https://pypi.org/project/brotli-middleware/), so the README should really suggest `pip install brotli-asgi`

**Comment by fullonic** [comment]
Hey @burritoIand sorry for the inconvenient. I forgot to update that part of the README file at time we switch the library name.
