### ISSUE TITLE
Gzip fallback

### ISSUE THREAD

**Issue by kylebarron** [fullonic/brotli-asgi#9]
Great package! Have you considered adding gzip as a fallback? Since brotli only has 94% browser coverage, I'd like to fall back to gzip, and not sure whether there's a place for that in this package.

**Comment by erichaus** [comment]
additionally does this package work with Mangum?

**Comment by kylebarron** [comment]
I haven't tested it yet, but it should... by the way I implemented gzip fallback here https://github.com/developmentseed/titiler/pull/116/files#diff-4155bc1b8eb5e5546f8e0062ac786025

**Comment by erichaus** [comment]
nice! that's helpful, I think I won't introduce brotli until having a fallback like that.. thanks for sharing

**Comment by fullonic** [comment]
Thanks for pointing out that situation @kylebarron

I think that should be a concern of the developer and not from this library. Also I think it's easier to implement when developing the server logic then do it here, inside this library. What do you think?

**Comment by kylebarron** [comment]
Personally I think it could make sense to have a gzip fallback within `brotli-asgi` because it wouldn't be a large change and you're already depending on `starlette`, so there's no additional dependencies.

I'd add just 1) an additional parameter `gzip_fallback: bool` and then 2) add here: https://github.com/fullonic/brotli-asgi/blob/dba50e09329c5b6abb415fcaa62b0a9e4065829c/brotli_asgi/__init__.py#L69

```py
if "gzip" in headers.get("Accept-Encoding", ""):
    responder = GZipResponder(self.app, self.minimum_size)
    await responder(scope, receive, send)
    return
```

Then a user could do just `BrotliMiddleware(**brotli_params, gzip_fallback = True)` and it would "just work"

**Comment by fullonic** [comment]
> nice! that's helpful, I think I won't introduce brotli until having a fallback like that.. thanks for sharing

You can easily do the fallback by yourself. For instance:
```python
if "br" in headers.get("Accept-Encoding", ""):
    # do your stuff with brotli
elif "gzip" in headers.get("Accept-Encoding", ""):
    # do your stuff with gzip

# or you can use a try except block if you know that will be almost the time brotli type. It's faster and more efficient 
# for example
try:
    assert "br" in headers.get("Accept-Encoding", "")
    # do your stuff with brotli
except AssertionError:
    # fallback to gzip or other

**Comment by fullonic** [comment]
I closed by mistake, sorry.

**Comment by fullonic** [comment]
> Personally I think it could make sense to have a gzip fallback within `brotli-asgi` because it wouldn't be a large change and you're already depending on `starlette`, so there's no additional dependencies.
> 
> I'd add just 1) an additional parameter `gzip_fallback: bool` and then 2) add here:
> 
> https://github.com/fullonic/brotli-asgi/blob/dba50e09329c5b6abb415fcaa62b0a9e4065829c/brotli_asgi/__init__.py#L69
> 
> ```python
> if "gzip" in headers.get("Accept-Encoding", ""):
>     responder = GZipResponder(self.app, self.minimum_size)
>     await responder(scope, receive, send)
>     return
> ```
> 
> Then a user could do just `BrotliMiddleware(**brotli_params, gzip_fallback = True)` and it would "just work"

Okay, that looks good. I was concern with having a auto fallback without developer control but your suggestion solves that. Would you like to create a new PR for it?
Thanks

**Comment by erichaus** [comment]
@kylebarron thanks all, https://sqwok.im now using brotli w/gzip fallback for api requests :D
